name: Build and Test (default)

on:
  push:
    branches:
      - 'develop'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  call-build:
    uses: ./.github/workflows/reusable-test-and-build.yml
    permissions:
      contents: read
    secrets: inherit
